name: CI
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.64.0, beta]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo test --all-features

      - run: rustup component add clippy
      - run: cargo clippy

      - run: rustup component add rustfmt
      - run: cargo fmt --check
